
CREATE TABLE personalname (
    idpersonalname NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    second_name VARCHAR2(100),
    first_lastname VARCHAR2(100) NOT NULL,
    second_lastname VARCHAR2(100)
);

CREATE TABLE userss (
    idUser NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) UNIQUE,
    email VARCHAR2(100) UNIQUE,
    password VARCHAR2(100),
    verifiedemail NUMBER(1) DEFAULT 0,
    idpersonalname NUMBER UNIQUE,
    CONSTRAINT fk_personalname_id FOREIGN KEY (idpersonalname) REFERENCES personalname(idpersonalname)
);


CREATE TABLE codigoverificacion (
    idCodigo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(10) NOT NULL,
    diaactual VARCHAR(10) NOT NULL,
    horaactual VARCHAR(8) NOT NULL,
    fechaCreacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    idUser NUMBER UNIQUE NOT NULL,
    CONSTRAINT fk_user_id FOREIGN KEY (idUser) REFERENCES userss(idUser)
);

CREATE TABLE rol (
    idrole INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rolecode VARCHAR2(20) NOT NULL,
    rolename VARCHAR2(100) NOT NULL
);

CREATE TABLE userrole (
    iduser NUMBER NOT NULL,
    idrole INTEGER NOT NULL,
    CONSTRAINT fk_user_role_id FOREIGN KEY (idUser) REFERENCES userss(idUser),
    CONSTRAINT fk_role_id FOREIGN KEY (idrole) REFERENCES Rol(idrole),
    PRIMARY KEY (iduser, idrole)
);


INSERT INTO rol (idrole, rolecode, rolename)
VALUES (1, 'BIBUSONL', 'Biblioteca en línea');

INSERT INTO rol (idrole, rolecode, rolename)
VALUES (2, 'SUPERADMIN', 'Administrador de acceso');

INSERT INTO rol (idrole, rolecode, rolename)
VALUES (3, 'BIBLIOTECARIO', 'Gestión bibliotecaria');

COMMIT;


/*

INSERT INTO userrole (iduser, idrole)
VALUES (1,2);

INSERT INTO userrole (iduser, idrole)
VALUES (21,3);


drop table codigoVerificacion;
drop table userss;
drop table personalname;
drop table userrole;
drop table rol;


select * from userrole;


SELECT * FROM rol WHERE idrole = 1

*/

