
CREATE TABLE personalname (
    idpersonalname NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    second_name VARCHAR2(100),
    first_lastname VARCHAR2(100) NOT NULL,
    second_lastname VARCHAR2(100)
);

CREATE TABLE userss (
    idUser NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) UNIQUE,
    email VARCHAR2(100) UNIQUE,
    password VARCHAR2(100),
    verifiedemail NUMBER(1) DEFAULT 0,
    idpersonalname NUMBER UNIQUE,
    CONSTRAINT fk_personalname_id FOREIGN KEY (idpersonalname) REFERENCES personalname(idpersonalname)
);


CREATE TABLE codigoverificacion (
    idCodigo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(10) NOT NULL,
    diaactual VARCHAR(10) NOT NULL,
    horaactual VARCHAR(8) NOT NULL,
    fechaCreacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    idUser NUMBER UNIQUE NOT NULL,
    CONSTRAINT fk_user_id FOREIGN KEY (idUser) REFERENCES userss(idUser)
);

CREATE TABLE rol (
    idrole INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rolecode VARCHAR2(20) NOT NULL,
    rolename VARCHAR2(100) NOT NULL
);

CREATE TABLE userrole (
    iduser NUMBER NOT NULL,
    idrole INTEGER NOT NULL,
    CONSTRAINT fk_user_role_id FOREIGN KEY (idUser) REFERENCES userss(idUser),
    CONSTRAINT fk_role_id FOREIGN KEY (idrole) REFERENCES Rol(idrole),
    PRIMARY KEY (iduser, idrole)
);

CREATE TABLE categoriaRecurso (
    idCategoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreCategoria VARCHAR2(20) NOT NULL,
    descripcionCategoria VARCHAR2(50)
);

CREATE TABLE editorial (
    ideditorial INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreeditorial VARCHAR2(50) NOT NULL,
    email VARCHAR2(30) NOT NULL,
    telefonoeditorial VARCHAR2(15) NOT NULL
);

CREATE TABLE idioma (
    idIdioma INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreIdioma VARCHAR2(30) NOT NULL,
    eliminado NUMBER(1) DEFAULT 0
);

CREATE TABLE autor (
    idautor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    second_name VARCHAR2(100),
    first_lastname VARCHAR2(100) NOT NULL,
    second_lastname VARCHAR2(100)
);

CREATE TABLE recursodigital (
    idRecursoDigital INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rutaAcceso VARCHAR2(1000),
    archivoDigitalData BLOB
);

CREATE TABLE libro (
    idLibro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(100) NOT NULL,
    fechaPublicacion VARCHAR(20),
    fechaAdquisicion VARCHAR(20),
    codigoISBN VARCHAR(50),
    descripcion VARCHAR(1000),
    edicion VARCHAR(50),
    numPaginas INTEGER,
    idCategoria INTEGER,
    idEditorial INTEGER,
    idIdioma INTEGER,
    idAutor INTEGER,
    idRecursoDigital INTEGER,
    eliminado NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_categoria FOREIGN KEY (idCategoria) REFERENCES categoriaRecurso(idCategoria),
    CONSTRAINT fk_editorial FOREIGN KEY (idEditorial) REFERENCES editorial(ideditorial),
    CONSTRAINT fk_idioma FOREIGN KEY (idIdioma) REFERENCES idioma(idIdioma),
    CONSTRAINT fk_autor FOREIGN KEY (idAutor) REFERENCES autor(idautor),
    CONSTRAINT fk_recursoDigital FOREIGN KEY (idRecursoDigital) REFERENCES recursodigital(idRecursoDigital)
);


INSERT INTO rol (idrole, rolecode, rolename)
VALUES (1, 'BIBUSONL', 'Biblioteca en línea');

INSERT INTO rol (idrole, rolecode, rolename)
VALUES (2, 'SUPERADMIN', 'Administrador de acceso');

INSERT INTO rol (idrole, rolecode, rolename)
VALUES (3, 'BIBLIOTECARIO', 'Gestión bibliotecaria');

COMMIT;


/*

INSERT INTO userrole (iduser, idrole)
VALUES (1,2);
COMMIT;

INSERT INTO userrole (iduser, idrole)
VALUES (21,3);


drop table codigoVerificacion;
drop table userss;
drop table personalname;
drop table userrole;
drop table rol;
drop table categoriarecurso;
drop table recursodigital;
drop table libro;


select * from userrole;


SELECT * FROM rol WHERE idrole = 1

*/

